query Tickets {
  listTickets(first: 10, sort: {field: INSERTED_AT, order: DESC}) @paginate(mode: SinglePage) {
    edges {
      node {
        id
        status
        subject
        insertedAt
        representative {
          id
          name
        }
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
