query Tickets {
  listTickets(first: 10) @paginate(mode: SinglePage) {
    edges {
      node {
        id
        status
        subject
        representative {
          id
          name
        }
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
